MOUSE_ROTATE_V = 1
MOUSE_ROTATE_H = 2
MOUSE_MOVE_V = 3
MOUSE_MOVE_H = 4
MOUSE_ZOOM = 5

mjOBJ_BODY = 1
mjOBJ_JOINT = 2

mjJNT_FREE  = 0
mjJNT_BALL  = 1
mjJNT_SLIDE = 2
mjJNT_HINGE = 3

# mjtCatBit - geom categories
mjCAT_STATIC = 1
mjCAT_DYNAMIC = 2
mjCAT_DECOR = 4
mjCAT_ALL = 7

# mjtPertBit - mouse perturbation
mjPERT_TRANSLATE = 1
mjPERT_ROTATE = 2

mjGEOM_ARROW = 100
mjGEOM_ARROW1 = 101
mjGEOM_ARROW2 = 102
mjGEOM_NONE = 1001
mjOBJ_UNKNOWN = 0
mjCAT_DECOR = 4
mjGEOM_CAPSULE = 3

